#!/usr/bin/env python

import apinger, socket, sys

def printer(ip, rtt):
    if not rtt:
        print '%20s %16s\tUNREACHABLE' % (ips[ip], ip)
    else:
        print '%20s %16s\t%.3f' % (ips[ip], ip, rtt)


if __name__ == '__main__':
    hosts_file = open(sys.argv[1])
    ips = dict()
    for line in hosts_file:
        (name, ip) = map(lambda k: k.strip(),  line.split('|'))
        ips[ip] = name
    hosts_file.close()
    apinger.loop(ips.keys(), printer)

